-- Consulta para ver todas las columnas de Staging_Activo
SELECT
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'Staging_Activo'
    AND COLUMN_NAME LIKE '%INPC%'
ORDER BY ORDINAL_POSITION;
